# {% set name = "traquitanas" %}
# {% set version = "1.0" %}

package:
  name: "traquitanas"
  version: "1.1.1"
  #name: "{{ name|lower }}"
  #version: "{{ version }}"

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: 5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7
  path: ..

build:
  number: 0
  #script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python
#    - pandas

# test:
#   imports:
#     - click

about:
  home: https://palletsprojects.com/p/click/
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Composable command line interface toolkit
  doc_url: https://badlands.readthedocs.io/
